In [ ]:
!pip install --user numpy

In [1]:
import numpy as np 


In [2]:
arr = np.array([1,2,3,4])
print(arr)


[1 2 3 4]


In [3]:
print(arr.shape)

(4,)


In [5]:
print("Dimension_of the array :", arr.ndim)

Dimension_of the array : 1


In [6]:
print("Size of the array :", arr.size)

Size of the array : 4


In [7]:
print("Data Type", arr.dtype)

Data Type int64


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
arr = np.array([[1,2,3], [3,4,5]])
print("Dimension :", arr.ndim)
print("Shape of the array : ", arr.shape)
print("*"*50)
print(arr)

Dimension : 2
Shape of the array :  (2, 3)
**************************************************
[[1 2 3]
 [3 4 5]]


In [17]:
arr = np.array([[[1,2,3], [3,4,5]], [[1,2,3], [3,4,5]]])
print("Dimension :", arr.ndim)
print("Shape of the array : ", arr.shape)
print("*"*50)
print(arr)

Dimension : 3
Shape of the array :  (2, 2, 3)
**************************************************
[[[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [3 4 5]]]


In [18]:
arr[1][1][2]

5

In [14]:
arr = np.array([[[[1,2,3], [3,4,5]], [[1,2,3], [3,4,5]]], [[[1,2,3], [3,4,5]], [[1,2,3], [3,4,5]]]])
print("Dimension :", arr.ndim)
print("Shape of the array : ", arr.shape)
print("*"*50)
print(arr)

Dimension : 4
Shape of the array :  (2, 2, 2, 3)
**************************************************
[[[[1 2 3]
   [3 4 5]]

  [[1 2 3]
   [3 4 5]]]


 [[[1 2 3]
   [3 4 5]]

  [[1 2 3]
   [3 4 5]]]]


In [15]:
arr[0][1][0][2]

3

In [16]:
arr[1][1][1][1]

4

In [19]:
arr = np.array(43)
print(arr.shape)
print(arr.ndim)

()
0


In [20]:
arr = np.array([[1,2,3], [4,5,6]], dtype='float')
print(arr)


[[1. 2. 3.]
 [4. 5. 6.]]


In [22]:
arr = np.zeros((3,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
arr = np.ones((4,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
arr = np.random.random((4,5))
print(arr)

[[0.59609938 0.25654437 0.47738698 0.08629938 0.04836533]
 [0.74390667 0.80788415 0.34780189 0.84888255 0.32913509]
 [0.9040475  0.08655975 0.4774808  0.32889247 0.3754782 ]
 [0.37513657 0.57480563 0.74471062 0.02616467 0.94348683]]


In [25]:
arr = np.arange(0, 50, 5)

In [26]:
print(arr)

[ 0  5 10 15 20 25 30 35 40 45]


In [28]:
arr = np.array([[1,2,3,4], [4,5,6,7], [7,8,9,2]])
print(arr.ndim)
print(arr.shape)
print(arr)


2
(3, 4)
[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 2]]


In [29]:
new_shape = arr.reshape(2,2,3)
print(new_shape)
print(new_shape.ndim)
print(new_shape.shape)

[[[1 2 3]
  [4 4 5]]

 [[6 7 7]
  [8 9 2]]]
3
(2, 2, 3)


In [30]:
arr = np.array([[2,3,4], [5,6,7]])
flat_arr = arr.flatten()
print(flat_arr)
print(flat_arr.ndim)

[2 3 4 5 6 7]
1


In [32]:
¸
print(arr[::2, ::3])
print(arr[0:1, :1])
print(arr[:, :1])

[[1 4]
 [8 2]]
[[1]]
[[1]
 [3]
 [8]
 [9]]


In [33]:
arr.flatten()

array([1, 2, 3, 4, 3, 5, 6, 7, 8, 3, 4, 2, 9, 5, 4, 2])

In [35]:
list(arr[:, :1].flatten())

[1, 3, 8, 9]

In [36]:
z = np.array([[[1,2,3], [3,4,5]], [[1,2,3], [3,4,5]]])

In [37]:
np.where(z== 5)

(array([0, 1]), array([1, 1]), array([2, 2]))

In [38]:
z.shape

(2, 2, 3)

In [ ]:
z[0][1][2]
z[1][1][2]